import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-layout">
          <div className="z-[1] flex flex-grow flex-col">
            <Header />
            <main className="container mx-auto flex-grow px-4">{children}</main>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
